// Generated by CoffeeScript 2.7.0
var autonomous, brain, comp, controller, pre_autonomous, user_control, x;

import {
  Brain,
  Competition,
  Controller,
  MSEC,
  wait
} from "./api/vex.js";

brain = Brain();

controller = Controller();

pre_autonomous = function() {
  return pass;
};

autonomous = function() {
  return pass;
};

user_control = function() {
  return wait(20, MSEC);
};

x = () => {
  return {"h": "h"};
};

console.log(x);

// create competition instance
comp = Competition(user_control, autonomous);

pre_autonomous();
